apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::252629378997:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-18KA5F7KSXMWZ
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::252629378997:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-08-15T18:10:04Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1524"
  uid: ca745804-728d-4ee3-bb6f-82a4fef0ef70
